---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: guestbook-app-latest
  namespace: guestbook-app
spec:
  type: GitHub
  pathname: https://github.com/mdelder/apps.git
  # secretRef:
  #   name: github-credentials
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: guestbook-app
  namespace: guestbook-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - guestbook-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: guestbook-app
  namespace: guestbook-app
  labels:
    app: guestbook-app
  annotations:
      apps.open-cluster-management.io/github-path: guestbook
spec:
  channel: guestbook-app/guestbook-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters