apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-ns-frontend-app-prod
  namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-project-frontend-app-prod-prod-ns
      spec:
        remediationAction: inform
        severity: medium
        namespaceSelector:
          exclude:
            - kube-*
          include:
            - default
        object-templates:
          - complianceType: musthave
            objectDefinition:
              kind: Namespace
              apiVersion: v1
              metadata:
                name: project-frontend-app-prod
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-ns-frontend-app-prod
  namespace: open-cluster-management-policies
placementRef:
  name: placement-policy-ns-frontend-app-prod
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-ns-frontend-app-prod
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-ns-frontend-app-prod
  namespace: open-cluster-management-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      []  # selects all clusters if not specified
