apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cluster-resume
  namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline configuration
spec:
  remediationAction: enforce
  disabled: true
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-cluster-resume
      spec:
        severity: high
        namespaceSelector:
          exclude:
            - kube-*
            - openshift-*
          include:
            - foxtrot-gcp-europe
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: hive.openshift.io/v1
              kind: ClusterDeployment
              metadata:
                name: foxtrot-gcp-europe
                namespace: foxtrot-gcp-europe
              spec:
                powerState: Running
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-cluster-resume-label
      spec:
        severity: high
        namespaceSelector:
          exclude:
            - kube-*
            - openshift-*
          include:
            - '*'
        object-templates:
          - complianceType: mustonlyhave
            objectDefinition:
              apiVersion: cluster.open-cluster-management.io/v1
              kind: ManagedCluster
              metadata:
                name: foxtrot-gcp-europe
                labels:
                  apps.ship-tracker: deployed
                  cloud: Google
                  clusterID: 5a5dff7f-0f3e-4ad9-ade3-e78cc21c1890
                  enforceSecureImages: "true"
                  name: foxtrot-gcp-europe
                  region: europe-west3
                  vendor: OpenShift
              spec:
                hubAcceptsClient: true
                leaseDurationSeconds: 60
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-cluster-resume
  namespace: open-cluster-management-policies
placementRef:
  name: placement-policy-cluster-resume
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-cluster-resume
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-cluster-resume
  namespace: open-cluster-management-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["local-cluster"]}