apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-project-frontend-app-prod
  namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline configuration
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-project-frontend-app-prod
      spec:
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - default
          - frontend-app-prod
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: project.openshift.io/v1
            kind: Project
            metadata:
              name: frontend-app-prod
          status:
            Validity: {}
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: LimitRange
            metadata:
              name: mem-limit-range
              namespace: frontend-app-prod
            spec:
              limits:
                - default:
                    memory: 512Mi
                  defaultRequest:
                    memory: 256Mi
                  type: Container
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-project-frontend-app-prod
  namespace: open-cluster-management-policies
placementRef:
  name: production-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-project-frontend-app-prod
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-project-frontend-app-prod
  namespace: open-cluster-management-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
