apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-rhsso-operator
  namespace: tower-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-rhsso-operator-project
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["*"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: project.openshift.io/v1
                kind: Project
                metadata:
                  name: keycloak
                spec: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-rhsso-operator
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          namespaceSelector:
            exclude: ["kube-*", "openshift-*"]
            include: ["keycloak"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: keycloak-group
                  namespace: keycloak
                spec:
                  targetNamespaces:
                  - keycloak
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-rhsso-operator
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          namespaceSelector:
            exclude: ["kube-*", "openshift-*"]
            include: ["keycloak"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: rhsso-operator
                  namespace: keycloak
                spec:
                  channel: alpha
                  installPlanApproval: Automatic
                  name: rhsso-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: rhsso-operator.7.4.5
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-rhsso-operator
  namespace: tower-policies
placementRef:
  name: placement-policy-rhsso-operator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-rhsso-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-rhsso-operator
  namespace: tower-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      []  # selects all clusters if not specified
    matchLabels:
      name: local-cluster
